### ISSUE TITLE
新增功能：申请重置奖励计时

### ISSUE THREAD

**Issue by phoenixlzx** [NyaaCat/PlayTimeTracker#4]
`rule` 添加一个属性 `re-acquire: true|false`。当为 `true` 时，条件满足的玩家可以通过 `/ptt reac [rule]` 来重新申请该奖励。

此功能旨在玩家不需要重置在线时间即可按规则重新积累时间来获得错过的奖励。

**Comment by RecursiveG** [comment]
这样一来就不仅要记录每个玩家的统计时间，还要记录每个玩家对每个reacquirable的奖励的统计时间。。。
DB又变复杂了。。。

**Comment by phoenixlzx** [comment]
reac 的请求单独记录一个文件里吧，应该只有非周期性的 rule 可以被 reac。

记录当前玩家的累积时间然后计算一个目标时间，达到后再次提醒玩家领取
