### ISSUE TITLE
空指针错误

### ISSUE THREAD

**Issue by Ghost-chu** [NyaaCat/PlayTimeTracker#9]
[Wed, 10. Jan 2018 22:08:33 CST INFO] MCYang issued server command: /ptt acquire day1hgift
[Wed, 10. Jan 2018 22:08:33 CST INFO] [Yum] [Yum 命令监控] 玩家 MCYang 执行 PlayTimeTracker 插件 ptt acquire day1hgift 命令时发生异常!
[Wed, 10. Jan 2018 22:08:33 CST INFO] [Yum] 异常名称: java.lang.NullPointerException
[Wed, 10. Jan 2018 22:08:33 CST INFO] [Yum] 异常说明: null
[Wed, 10. Jan 2018 22:08:33 CST INFO] [Yum] 简易错误信息如下:
[Wed, 10. Jan 2018 22:08:33 CST INFO] [Yum]     位于 com.mcml.space.monitor.MonitorUtils.AExceptionCatcher(MonitorUtils.java:46)
[Wed, 10. Jan 2018 22:08:33 CST INFO] [Yum]     位于 com.mcml.space.monitor.inject.CommandInjector.onCommand(CommandInjector.java:103)
[Wed, 10. Jan 2018 22:08:33 CST INFO] [Yum]     位于 org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[Wed, 10. Jan 2018 22:08:33 CST INFO] [Yum]     位于 org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[Wed, 10. Jan 2018 22:08:33 CST INFO] [Yum]     位于 org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:648)

附上配置文件:
message:
  prefix: "§8§l[§d§l在线时长§8§l]§a"

  have-reward-redeem: "§d你有未领取的时长奖励, 使用 `/ptt acquire` 来领取全部时长奖励"
  have-reward-redeem-format: "- %s"
  rule-applied: "§a恭喜！您可以领取奖励 %s"
  nothing-to-acquire: "§a您还没有可以领取的奖励"
  cannot-acquire: "§a你现在还不能领取奖励 %s !"
  no-such-rule: "§a没有找到该奖励"

  only-player-can-do: "§c只有玩家可以这样做!"
  no-permission: "§c抱歉 你没有这么做的权限!"
  reload-finished: "§a重载完成"
  command-done: "§a命令执行成功"

  statistic-for: "§b玩家 %s 的在线统计信息:"
  statistic-day: "§b今日在线时长: %s"
  statistic-week: "§b本周在线时长: %s"
  statistic-month: "§b本月在线时长: %s"
  statistic-session: "§b本次登陆在线时长: %s"
  statistic-total: "§b累计在线时长: %s"
  statistic-time-format:
    ms: "%d毫秒"
    s: "%d秒 "
    m: "%d分钟 "
    h: "%d小时 "
    zero: "无记录"
  statistic-no-record: "没有这个玩家的数据."

  no-player: "玩家不存在."
  invalid-rule: "不是有效的一次性奖励规则"

ignore-afk: true
save-interval: 60 #seconds
display-on-login: true

rewards:
  EveryDay1h:
    description: "你获得了30弹珠"
    command: "money grant {playerName} 30"
  EveryWeek24h:
    description: "你获得了100弹珠"
    command: "money grant {playerName} 100"
  EveryMonth7Day :
    description: "你获得了200弹珠"
    command: "money grant {playerName} 200"

rules:
  Day1hGIFT: # rule name cannot contains space ` ` and comma `,`
    period: "day" # week|month|disposable|session #一天内满1小时在线
    require: 60 # total online *minutes* to meet the reward requirement
    auto-give: false # automatically give the reward
    timeout: 60 # the time player able to acquire the reward, in minutes.
                # Ignored when auto-give is true. Omit this means "unlimited".
                # Always timeout at the end of each period
    reward: EveryDay1h
  Week24hGIFT:
    period: "week"
    require: 1440
    auto-give: true
    timeout: 120
    reward: EveryWeek24h
  Month7dayGIFT: #一个月有7整天在线
    period: "month"
    require: 10080
    auto-give: true
    timeout: 10080
    reward: EveryMonth7Day 
 #rule3:
   # period: "longtimenosee" # rewards are given when players back after a long period time of away
    #require: 60 # how long the player left, *IN DAYS*
    #auto-give: true
    #eligible-group: [group1,group2] # only players in groups listed here can acquire the rule. Any one can acquire if omitted.
    #reward: another-reward

运行环境:
Spigot 1.12.2 Java8

**Comment by cyilin** [comment]
看上去并不是ptt的问题，而是服务器在执行奖励中指定的命令时出现的异常，那个命令可以在终端中正常执行吗？

**Comment by Ghost-chu** [comment]
可以正常执行的

**Comment by Ghost-chu** [comment]
还真是指令报错 感谢
